"""Added tables Company, Message, Mail

Revision ID: 645356fc502b
Revises: d0569ca3ea3d
Create Date: 2019-11-10 15:28:05.585325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '645356fc502b'
down_revision = 'd0569ca3ea3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('address', sa.String(length=150), nullable=True),
    sa.Column('postal_code', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('province', sa.String(length=64), nullable=True),
    sa.Column('phone1', sa.String(length=64), nullable=True),
    sa.Column('phone2', sa.String(length=64), nullable=True),
    sa.Column('fax', sa.String(length=64), nullable=True),
    sa.Column('client_since', sa.DateTime(), nullable=True),
    sa.Column('cif', sa.String(length=64), nullable=True),
    sa.Column('IBAN', sa.String(length=64), nullable=True),
    sa.Column('products', sa.PickleType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_cif'), 'company', ['cif'], unique=True)
    op.create_index(op.f('ix_company_email'), 'company', ['email'], unique=True)
    op.create_index(op.f('ix_company_fax'), 'company', ['fax'], unique=False)
    op.create_index(op.f('ix_company_identifier'), 'company', ['identifier'], unique=True)
    op.create_index(op.f('ix_company_name'), 'company', ['name'], unique=True)
    op.create_index(op.f('ix_company_phone1'), 'company', ['phone1'], unique=False)
    op.create_table('my_company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('address', sa.String(length=150), nullable=True),
    sa.Column('postal_code', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('province', sa.String(length=64), nullable=True),
    sa.Column('phone1', sa.String(length=64), nullable=True),
    sa.Column('phone2', sa.String(length=64), nullable=True),
    sa.Column('fax', sa.String(length=64), nullable=True),
    sa.Column('cif', sa.String(length=64), nullable=True),
    sa.Column('iva', sa.Float(), nullable=True),
    sa.Column('IBAN', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_my_company_cif'), 'my_company', ['cif'], unique=True)
    op.create_index(op.f('ix_my_company_email'), 'my_company', ['email'], unique=True)
    op.create_index(op.f('ix_my_company_fax'), 'my_company', ['fax'], unique=False)
    op.create_index(op.f('ix_my_company_name'), 'my_company', ['name'], unique=True)
    op.create_index(op.f('ix_my_company_phone1'), 'my_company', ['phone1'], unique=False)
    op.create_table('email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_timestamp'), 'email', ['timestamp'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('company_id', sa.String(length=64), nullable=True),
    sa.Column('tutorials', sa.Boolean(), nullable=True),
    sa.Column('permissions', sa.Enum('owner', 'admin', 'user', name='permissionsenum'), nullable=True),
    sa.Column('last_message_read_time', sa.DateTime(), nullable=True),
    sa.Column('token', sa.String(length=32), nullable=True),
    sa.Column('token_expiration', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['my_company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_token'), 'user', ['token'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_timestamp'), 'message', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_timestamp'), table_name='message')
    op.drop_table('message')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_token'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_email_timestamp'), table_name='email')
    op.drop_table('email')
    op.drop_index(op.f('ix_my_company_phone1'), table_name='my_company')
    op.drop_index(op.f('ix_my_company_name'), table_name='my_company')
    op.drop_index(op.f('ix_my_company_fax'), table_name='my_company')
    op.drop_index(op.f('ix_my_company_email'), table_name='my_company')
    op.drop_index(op.f('ix_my_company_cif'), table_name='my_company')
    op.drop_table('my_company')
    op.drop_index(op.f('ix_company_phone1'), table_name='company')
    op.drop_index(op.f('ix_company_name'), table_name='company')
    op.drop_index(op.f('ix_company_identifier'), table_name='company')
    op.drop_index(op.f('ix_company_fax'), table_name='company')
    op.drop_index(op.f('ix_company_email'), table_name='company')
    op.drop_index(op.f('ix_company_cif'), table_name='company')
    op.drop_table('company')
    # ### end Alembic commands ###
