"""Added customers and users relationships

Revision ID: aef012f7302b
Revises: 645356fc502b
Create Date: 2019-11-13 18:22:37.856945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aef012f7302b'
down_revision = '645356fc502b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('vendor', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_company_identifier'), 'company', ['identifier'], unique=True)
    op.drop_index('ix_company_ID', table_name='company')
    op.create_foreign_key(None, 'company', 'my_company', ['vendor'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'company', type_='foreignkey')
    op.create_index('ix_company_ID', 'company', ['id'], unique=1)
    op.drop_index(op.f('ix_company_identifier'), table_name='company')
    op.drop_column('company', 'vendor')
    # ### end Alembic commands ###
