"""Added tables Company, Message, Mail

Revision ID: d0569ca3ea3d
Revises: f6814191c813
Create Date: 2019-11-10 15:23:15.091480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0569ca3ea3d'
down_revision = 'f6814191c813'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ID', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('address', sa.String(length=150), nullable=True),
    sa.Column('postal_code', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('province', sa.String(length=64), nullable=True),
    sa.Column('phone1', sa.String(length=64), nullable=True),
    sa.Column('phone2', sa.String(length=64), nullable=True),
    sa.Column('fax', sa.String(length=64), nullable=True),
    sa.Column('client_since', sa.DateTime(), nullable=True),
    sa.Column('cif', sa.String(length=64), nullable=True),
    sa.Column('IBAN', sa.String(length=64), nullable=True),
    sa.Column('products', sa.PickleType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_ID'), 'company', ['ID'], unique=True)
    op.create_index(op.f('ix_company_cif'), 'company', ['cif'], unique=True)
    op.create_index(op.f('ix_company_email'), 'company', ['email'], unique=True)
    op.create_index(op.f('ix_company_fax'), 'company', ['fax'], unique=False)
    op.create_index(op.f('ix_company_name'), 'company', ['name'], unique=True)
    op.create_index(op.f('ix_company_phone1'), 'company', ['phone1'], unique=False)
    op.create_table('email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_timestamp'), 'email', ['timestamp'], unique=False)
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_timestamp'), 'message', ['timestamp'], unique=False)
    op.add_column('user', sa.Column('last_message_read_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_message_read_time')
    op.drop_index(op.f('ix_message_timestamp'), table_name='message')
    op.drop_table('message')
    op.drop_index(op.f('ix_email_timestamp'), table_name='email')
    op.drop_table('email')
    op.drop_index(op.f('ix_company_phone1'), table_name='company')
    op.drop_index(op.f('ix_company_name'), table_name='company')
    op.drop_index(op.f('ix_company_fax'), table_name='company')
    op.drop_index(op.f('ix_company_email'), table_name='company')
    op.drop_index(op.f('ix_company_cif'), table_name='company')
    op.drop_index(op.f('ix_company_ID'), table_name='company')
    op.drop_table('company')
    # ### end Alembic commands ###
